version: "3.9"
services:

#################### traefik
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=email@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CLOUDFLARE_EMAIL=${cloudflare_email}
      - CLOUDFLARE_DNS_API_TOKEN=${cloudflare_dns_api_token}
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

#################### whoami
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`docshouse.cc`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

# #################### whoami
#   whoami:
#     image: "traefik/whoami"
#     container_name: whoami
#     scale: 1
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.whoami.rule=Host(`10.0.0.21`) && Path(`/whoami`)"
#       - "traefik.http.routers.whoami.entrypoints=web"

  whoami2:
    image: "nginxdemos/hello"
    container_name: whoami2
    scale: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.rule=Host(`10.0.0.21`) && Path(`/whoami2`)"
      - "traefik.http.routers.whoami2.entrypoints=web"

#################### portainer
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "9000:9000"
    volumes:
      - $docker_dir/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

#################### watchtower
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 9 * * SUN" --cleanup
    environment:
      - NETWORK_ACCESS=internal
    restart:
      always 

################### heimdall
  # heimdall:
  #   image: ghcr.io/linuxserver/heimdall
  #   container_name: heimdall
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Dublin
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.heimdall.rule=Host(`0.0.0.0`) && Path(`/heimdall`)"
  #     - "traefik.http.routers.heimdall.entrypoints=web"
  #   volumes:
  #     - $docker_dir/appdata/heimdall:/config
  #   restart:
  #     always

#################### mqtt
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - $docker_dir/appdata/mosquitto/config:/mosquitto/config
      - $docker_dir/appdata/mosquitto/data:/mosquitto/data
      - $docker_dir/appdata/mosquitto/log:/mosquitto/log
    restart:
      always
    networks:
      - mosquitto

##################### node-red
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Dublin
      - PUID=1000
      - PGID=1000
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - $docker_dir/appdata/node_red/data:/data      


#---------- influxdb ----------#
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - $docker_dir/appdata/influxdb2/config:/etc/influxdb2
      - $docker_dir/appdata/influxdb2/db:/var/lib/influxdb2


#---------- grafana ----------#
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    ports:
      - "3000:3000"
    user: "1000"
    volumes:
      - $docker_dir/appdata/grafana:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"


networks:
    mosquitto:
        name: mosquitto
        driver: bridge
    node-red-net:
        name: node-red-net
        driver: bridge        
