services:
#################### portainer
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "9000:9000"
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

#################### watchtower
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 9 * * SUN" --cleanup
    environment:
      - NETWORK_ACCESS=internal
    restart:
      always 

################### heimdall
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "443:443"
    volumes:
      - /opt/appdata/heimdall:/config
    restart:
      always

#################### mqtt
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - /opt/appdata/mosquitto/config:/mosquitto/config
      - /opt/appdata/mosquitto/data:/mosquitto/data
      - /opt/appdata/mosquitto/log:/mosquitto/log
    restart:
      always
    networks:
      - mosquitto

##################### node-red
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - /opt/appdata/node_red/data:/data      

networks:
    mosquitto:
        name: mosquitto
        driver: bridge
    node-red-net:
        name: node-red-net
        driver: bridge        