### This playbook will provision the full environment.
### Before running this playbook add the ansible ssh key to the server(s)
### ssh-copy-id -i ~/.ssh/ansible.pub serverip
---

  - name: provision servers
    hosts: 10.0.0.21
    become: true
    vars_files:
      - vars.yml

    tasks:


#---------- Update Repos ----------#

    - name: update repository index
      apt:
        update_cache: yes


#---------- Install and enable qemu agent ----------#

    - name: install qemu agent
      apt:
        name: qemu-guest-agent
        state: latest


    - name: start qemu-agent
      ansible.builtin.systemd:
        state: started
        name: qemu-guest-agent


    - name: enable qemu-agent
      ansible.builtin.systemd:
        enabled: yes
        name: qemu-guest-agent


#---------- Install rsync ----------#

    - name: install rsync
      apt:
        name: rsync
        state: latest        


#---------- Install cron ----------#

    - name: Install cron
      apt:
        name: cron
        state: latest
        update_cache: true        


#---------- Install Docker ----------#

    - name: create containers directory
      file:
        path: "{{ docker_dir }}"
        state: directory

    - name: copy docker .env to the server(s)
      ansible.builtin.copy:
        src: "{{ config_files_source }}/.env"
        dest: "{{ docker_dir }}/.env"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g=r,o=r

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Add user to docker group
      user:
        name: "{{ user }}"
        group: docker


#---------- Install Docker Compose ----------#

    - name: Download docker-compose {{ docker_compose_version }}
      get_url:
        url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: ~/docker-compose
        mode: '+x'

    - name: Check docker-compose exists
      stat: path=~/docker-compose
      register: docker_compose

    - name: Move docker-compose to /usr/local/bin/docker-compose
      command: mv ~/docker-compose /usr/local/bin/docker-compose
      when: docker_compose.stat.exists

#---------- Copy docker-compose.yml to the server ----------#

    - name: copy docker-compose.yml to the server(s)
      ansible.builtin.copy:
        src: "{{ config_files_source }}/docker-compose.yml"
        dest: "{{ docker_dir }}/docker-compose.yml"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g=r,o=r

#---------- Configure mosquitto ----------#

    - name: create directory /appdata/mosquitto/config
      file:
        path: "{{ docker_dir }}/appdata/mosquitto/config"
        state: directory


    - name: copy mosquitto.conf to the server(s)
      ansible.builtin.copy:
        src: "{{ config_files_source }}/mosquitto.conf"
        dest: "{{ docker_dir }}/appdata/mosquitto/config/mosquitto.conf"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g=r,o=r

    - name: copy mosquitto.passwd to the server(s)
      ansible.builtin.copy:
        src: "{{ config_files_source }}/mosquitto.passwd"
        dest: "{{ docker_dir }}/appdata/mosquitto/config/mosquitto.passwd"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g=r,o=r

#---------- Configure grafana directory permissions----------#

    - name: create directory /appdata/grafana
      file:
        path: "{{ docker_dir }}/appdata/grafana"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g=r,o=r

##---------- Mount container_backups----------#

    - name: Mount backups CIFS volume
      ansible.posix.mount:
        src: //10.0.0.8/container_backups
        path: /mnt/container_backups
        opts: "rw,vers=3,file_mode=0600,dir_mode=0700,username={{ smb_username }},password={{ smb_password }}"
        boot: true
        state: mounted
        fstype: cifs

#---------- Set /mnt/container_backups folder ownership ----------#

    - name: Set node-red folder ownership
      ansible.builtin.file:
        path: /mnt/container_backups
        state: directory
        recurse: yes
        owner: "{{ user }}"
        group: "{{ user }}"

##---------- Restore container_backups----------#

    - name: excecute rysnc restore
      ansible.builtin.shell: rsync -azv /mnt/container_backups/ /home/john/containers/appdata/

#---------- Run docker-compose.yml ----------#

    - name: move to {{ docker_dir }} and run docker-compose.yml
      ansible.builtin.shell: cd {{ docker_dir }} && docker-compose -f docker-compose.yml up -d --remove-orphans


#---------- Configure grafans permissions ----------#

    - name: Set grafana directory permissions
      ansible.builtin.file:
        path: "{{ docker_dir }}/appdata/grafana"
        state: directory
        recurse: yes
        owner: "{{ 472 }}"
        group: "{{ 0 }}"

    - name: start the grafana container
      ansible.builtin.shell: docker start grafana

#---------- Configure node-red ----------#

    - name: Set node-red folder ownership
      ansible.builtin.file:
        path: "{{ docker_dir }}/appdata/node_red"
        state: directory
        recurse: yes
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: start the node-red container
      ansible.builtin.shell: docker start node-red

#---------- Configure tailscale ----------#
    roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ TAILSCALE_KEY }}"

#---------- Reinstate backups ----------#

    - name: Creates a cron file under /etc/cron.d
      ansible.builtin.cron:
        name: ansible_container_update
        weekday: "*"
        minute: "0"
        hour: "3"
        user: root
        job: "rsync -azv /home/john/containers/appdata/ /mnt/container_backups/"
        cron_file: ansible_container_update
