---
- name: allow 'john' to run rsync without sudo password
  hosts: 10.0.0.21
  become: true
  tasks:
    - name: edit sudoers file
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^john'
        line: 'john ALL=(ALL) NOPASSWD:/usr/bin/rsync'
        validate: 'visudo -cf %s'