---
- hosts: 10.0.0.21
  become: true
  tasks:




    - name: move to /opt and run docker-compose.yml
      ansible.builtin.shell: cd /opt && docker-compose -f docker-compose.yml up -d --remove-orphans