---
- hosts: 10.0.0.21
  become: true
  roles:
    - role: artis3n.tailscale
      vars:
        # Example pulling the API key from the env vars on the host running Ansible
        #tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_authkey: "{{ TAILSCALE_KEY }}"
        #tailscale_authkey: "tskey-auth-kTUbGy5CNTRL-kHBBYTPwJLf5B2jFiLQSTfc52Avhf6cw"
