---

  - name: install_qemu_agent
    hosts: ubuntu_servers
    become: true
    tasks:
  
    - name: update repository index
      apt:
        update_cache: yes
  
    - name: install qemu agent
      apt:
        name: qemu-guest-agent
        state: latest
  
    - name: start qemu-agent
      ansible.builtin.systemd:
        state: started
        name: qemu-guest-agent

    - name: enable qemu-agent
      ansible.builtin.systemd:
        enabled: yes
        name: qemu-guest-agent     
