---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Update all Ubuntu packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Upgrade the Ubuntu servers OS (apt-get dist-upgrade)
    ansible.builtin.apt:
      upgrade: dist
    when: ansible_distribution == "Ubuntu"